In [1]:
from transformers import BartTokenizer, BartForConditionalGeneration
from transformers.modeling_outputs import BaseModelOutput
from IPython.display import display, HTML
import torch

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load BART model and tokenizer
model_name = "facebook/bart-base"  # Choose your preferred BART model
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name).to(device)

In [2]:
def add_noise_with_snr(encoder_output, target_snr_db):
    """
    Add noise to the encoder output based on a target SNR in dB.
    
    Parameters:
    - encoder_output: torch.Tensor, the encoder's output (last_hidden_state).
    - target_snr_db: float, the desired signal-to-noise ratio in dB.
    
    Returns:
    - noisy_encoder_output: torch.Tensor, encoder output with added noise.
    """
    # Convert SNR from dB to linear scale
    target_snr_linear = 10 ** (target_snr_db / 10)
    
    # Calculate power of the signal
    signal_power = torch.mean(encoder_output ** 2)
    
    # Calculate required noise power for the target SNR
    noise_power = signal_power / target_snr_linear
    noise = torch.randn_like(encoder_output) * torch.sqrt(noise_power)
    
    # Add noise to the encoder output
    noisy_encoder_output = encoder_output + noise
    return noisy_encoder_output


In [3]:
original_text = """
Beginners BBQ Class Taking Place in Missoula! 
Do you want to get better at making delicious BBQ?
You will have the opportunity, put this on your calendar now. 
Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. 
He will be teaching a beginner level class for everyone who wants to get better with their culinary skills. 
He will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information. 
The cost to be in the class is $35 per person, and for spectators it is free. 
Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.
"""
input_text = """
Beginners BBQ Class <mask> in Missoula! 
Do you want to <mask> making delicious BBQ?
You will have the opportunity, put this on your calendar now. 
Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. 
He will be teaching a beginner level class for everyone who wants to get better with their culinary skills. 
He will teach you <mask> compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information. 
The <mask> the class is $35 per person, and for spectators it is free. 
Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.
""".replace("\n", "")


# original_text = """
# This November, embark on an exciting hiking adventure! 
# Explore the scenic mountain trails with an experienced guide, who will show you the best routes and hidden viewpoints. 
# This journey is suitable for all levels, from beginners to advanced hikers. 
# The hike covers approximately 10 miles and includes multiple rest stops with breathtaking views. 
# Participants should bring water, snacks, and comfortable hiking shoes. 
# The cost of the trip is $60, which includes a map and a group photo.
# """
# input_text = """
# This November, embark on an exciting <mask> adventure! 
# Explore the scenic mountain trails with an experienced guide, who will show you the best routes and hidden <mask>. 
# This journey is suitable for all levels, from beginners to advanced <mask>. 
# The hike covers approximately 10 miles and includes multiple rest stops with breathtaking <mask>. 
# Participants should bring water, snacks, and comfortable hiking shoes. 
# The <mask> is $60, which includes a map and a group photo.
# """.replace("\n", "")

# original_text = """
# Welcome to our online coding bootcamp program! 
# Whether you're a complete beginner or looking to improve your programming skills, this course is designed for you. 
# Throughout the course, you will learn essential coding languages such as Python and JavaScript. 
# Our instructors will guide you through interactive projects and provide real-time feedback. 
# Each student will receive a certificate of completion at the end of the program. 
# The total cost for the bootcamp is $150, which includes all learning materials.
# """
# input_text = """
# Welcome to our online <mask> bootcamp program! 
# Whether you're a complete beginner or looking to <mask> your programming skills, this course is designed for you. 
# Throughout the course, you will learn essential <mask> such as Python and JavaScript. 
# Our instructors will guide you through interactive projects and provide real-time <mask>. 
# Each student will receive a certificate of completion at the end of the <mask>. 
# The total cost for the bootcamp is $150, which <mask> all learning materials.
# """.replace("\n", "")

In [5]:
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to(device)

# Get encoder output without noise
with torch.no_grad():
    encoder_outputs = model.model.encoder(input_ids=input_ids)

# Generate output without noise
baseline_outputs = model.generate(
    input_ids=None,
    encoder_outputs=encoder_outputs,
    max_length=200,
    do_sample=True,
    temperature=0.1
)
baseline_text = tokenizer.decode(baseline_outputs[0], skip_special_tokens=True)

# Add noise with a target SNR and generate noisy output
target_snr = 3  # Set target SNR
noisy_encoder_output = add_noise_with_snr(encoder_outputs.last_hidden_state, target_snr)
modified_encoder_outputs = BaseModelOutput(last_hidden_state=noisy_encoder_output)

# Generate output with the noisy encoder output
noisy_outputs = model.generate(
    input_ids=None,
    encoder_outputs=modified_encoder_outputs,
    max_length=200,
    do_sample=True,
    temperature=0.1
)
noisy_text = tokenizer.decode(noisy_outputs[0], skip_special_tokens=True)
noisy_text_1 = tokenizer.decode(noisy_outputs[1], skip_special_tokens=True)

# Display both outputs
print('Original Text:')
display(HTML(f"<p style='font-size:15px; font-family:\"Comic Sans MS\", cursive;'> {original_text}</p>"))
print('Without Noise:')
display(HTML(f"<p style='font-size:15px; font-family:\"Comic Sans MS\", cursive;'>{baseline_text}</p>"))
print(f'With Noise (SNR = {target_snr} dB):')
display(HTML(f"<p style='font-size:15px; font-family:\"Comic Sans MS\", cursive;'>{noisy_text}</p>"))
print(f'With Noise (SNR = {target_snr} dB):')
display(HTML(f"<p style='font-size:15px; font-family:\"Comic Sans MS\", cursive;'>{noisy_text_1}</p>"))

Original Text:


Without Noise:


With Noise (SNR = 3 dB):


With Noise (SNR = 3 dB):


In [68]:
tokenizer.decode(, skip_special_tokens=True)

''

In [63]:
# baseline_outputs.shape
noisy_outputs.shape

torch.Size([4, 168])

In [64]:
baseline_outputs[0]

tensor([    2,     0, 48290,  7130, 22658,  4210,    23,   226, 28180,   271,
        21389,  5706,    11,  4523,  5156,   102,   328,  1832,    47,   236,
            7,   120,   554,    15,   442, 10964, 22658,   116,  1185,    40,
           33,     5,   945,     6,   342,    42,    15,   110,  7127,   122,
            4,   296,     6,   772,   820,  1187,  1962,   623,  4210, 22658,
        10078,     6,  3621,  4317,   857,    31,   226, 28180,  2747, 21389,
         5706,     4,    91,    40,    28,  5307,    10, 37239,   672,  1380,
           13,   961,    54,  1072,     7,   120,   357,    19,    49, 16820,
         2417,     4,    91,    16,  5307,    47,   141,     7,  3886,     8,
         3511,    11,    10,   229,  8949, 22658,  1465,     6,   217,  7373,
            6, 13204,     6, 31583,     6,  4884,  4230,     8, 10723,  7059,
            6,  2704, 40345,     8,   668,   335,     4,    20,   701,     9,
            5,  1380,    16,    68,  2022,   228,   621,     6, 

In [65]:
noisy_outputs[0]

tensor([    2,     0, 48290,  7130, 22658,  4210,    23,   226, 28180,   271,
        21389,  5706,    11,  4523,  5156,   102,   328,  1832,    47,   236,
            7,   120,   554,    15,   442, 10964, 22658,   116,  1185,    40,
           33,     5,   945,     6,   342,    42,    15,   110,  7127,   122,
            4,   296,     6,   772,   820,  1187,  1962,   623,  4210, 22658,
        10078,     6,  3621,  4317,   857,    31,   226, 28180,  1766, 21389,
         5706,     4,    91,    40,    28,  5307,    10, 37239,   672,  1380,
           13,   961,    54,  1072,     7,   120,   357,    19,    49, 16820,
         2417,     4,    91,    16,  6396,    47,   141,     7,   146,    10,
        10964, 22658,     8,   172,  3511,    11,    10,   229,  8949, 22658,
         1465,     6,   217,  7373,     6, 13204,     6, 31583,     6,  4884,
         4230,     8, 10723,  7059,     6,  2704, 40345,     8,   668,   335,
            4,    20,   701,     9,     5,  1380,    16,    68, 

In [67]:
import torch.nn.functional as F
from sklearn.metrics import mean_absolute_percentage_error

baseline = baseline_outputs[0].cpu()
noisy = noisy_outputs[0].cpu()
max_len = max(baseline.size(0), noisy.size(0))
baseline_padded = F.pad(baseline, (0, max_len - baseline.size(0)))
noisy_padded = F.pad(noisy, (0, max_len - noisy.size(0)))
mse = mean_squared_error(baseline_padded, noisy_padded)
mse

np.float64(6.6562130206910536e+16)

In [69]:
baseline_padded

tensor([    2,     0, 48290,  7130, 22658,  4210,    23,   226, 28180,   271,
        21389,  5706,    11,  4523,  5156,   102,   328,  1832,    47,   236,
            7,   120,   554,    15,   442, 10964, 22658,   116,  1185,    40,
           33,     5,   945,     6,   342,    42,    15,   110,  7127,   122,
            4,   296,     6,   772,   820,  1187,  1962,   623,  4210, 22658,
        10078,     6,  3621,  4317,   857,    31,   226, 28180,  2747, 21389,
         5706,     4,    91,    40,    28,  5307,    10, 37239,   672,  1380,
           13,   961,    54,  1072,     7,   120,   357,    19,    49, 16820,
         2417,     4,    91,    16,  5307,    47,   141,     7,  3886,     8,
         3511,    11,    10,   229,  8949, 22658,  1465,     6,   217,  7373,
            6, 13204,     6, 31583,     6,  4884,  4230,     8, 10723,  7059,
            6,  2704, 40345,     8,   668,   335,     4,    20,   701,     9,
            5,  1380,    16,    68,  2022,   228,   621,     6, 

In [42]:
 max_shape

torch.Size([163])

## bart-base seems to be better than bart-large