In [7]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
from transformers.modeling_outputs import BaseModelOutput
import torch

model_name = "google/flan-t5-base"
tokenizer = T5Tokenizer.from_pretrained(model_name)

In [8]:
input_text = "I live in Beijing."
input_ids = tokenizer(input_text, return_tensors="pt")
input_ids['input_ids']

tensor([[   27,   619,    16, 14465,     5,     1]])

In [9]:
from transformers import BartTokenizer, BartForConditionalGeneration
from transformers.modeling_outputs import BaseModelOutput
from IPython.display import display, HTML
import torch

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load BART model and tokenizer
model_name = "facebook/bart-base"  # Choose your preferred BART model
tokenizer = BartTokenizer.from_pretrained(model_name)

In [10]:
input_text = "I live in Beijing."
input_ids = tokenizer(input_text, return_tensors="pt")
input_ids['input_ids']

tensor([[   0,  100,  697,   11, 3332,    4,    2]])

In [14]:
input_text = "I live in Stockholm."
input_ids = tokenizer(input_text, return_tensors="pt")
input_ids['input_ids']

tensor([[    0,   100,   697,    11, 18850,     4,     2]])

In [13]:
tokenizer.decode(input_ids['input_ids'][0],  skip_special_tokens=True)

'I live in Stockholm.'

In [4]:
from transformers import AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("Falconsai/text_summarization")

In [5]:
input_text = "I live in Beijing."
input_ids = tokenizer(input_text, return_tensors="pt")
input_ids['input_ids']

tensor([[   27,   619,    16, 14465,     5,     1]])

In [7]:
tt = torch.tensor([0, 66,666,     5,     1,])
t = tokenizer.decode(tt)
t

'<pad> all below.</s>'